apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-12.6
  labels:
    app: deployment-12.6
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-12.6
  template:
    metadata:
      labels:
        app: deployment-12.6
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ['sh', '-c', 'while true; do echo Hello user! >> /busybox/Hello.txt; sleep 5; done']
        volumeMounts:
          - mountPath: /busybox
            name: first-volume
        imagePullPolicy: IfNotPresent
      - image: wbitt/network-multitool
        name: multitool
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /moltitool
            name: first-volume
        imagePullPolicy: IfNotPresent
      volumes:
        - name: first-volume
          hostPath:
            path: /k8s_base/12.6/12.6.1
